### ISSUE TITLE
After login - Account is pointing to different account

### ISSUE THREAD

**Issue by HemanthKum4r** [humanbeeng/checkpost#136]
<img width="1680" alt="Screenshot 2024-06-25 at 9 43 52 AM" src="https://github.com/humanbeeng/checkpost/assets/143784998/a54d29b1-0c05-46ab-9d4f-2ec2b9da34eb">

My dashboard after login

**Comment by humanbeeng** [comment]
Fixed in https://github.com/humanbeeng/checkpost/pull/140
